# Generated by Django 4.1.7 on 2023-03-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseMarginReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clearing_member",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="clearing member"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="account"
                    ),
                ),
                (
                    "margin_class",
                    models.CharField(
                        choices=[
                            ("span", "Span"),
                            ("imsm", "Imsm"),
                            ("cesm", "Cesm"),
                            ("ampo", "Ampo"),
                            ("amem", "Amem"),
                            ("amco", "Amco"),
                            ("amcu", "Amcu"),
                            ("amwi", "Amwi"),
                            ("dmem", "Dmem"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="margin type",
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="margin"
                    ),
                ),
                (
                    "report_date",
                    models.DateField(db_index=True, verbose_name="report date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CC050",
            fields=[
                (
                    "basemarginreport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="margin_check.basemarginreport",
                    ),
                ),
            ],
            bases=("margin_check.basemarginreport",),
        ),
        migrations.CreateModel(
            name="CI050",
            fields=[
                (
                    "basemarginreport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="margin_check.basemarginreport",
                    ),
                ),
                ("report_time", models.TimeField(verbose_name="report time")),
            ],
            bases=("margin_check.basemarginreport",),
        ),
    ]
