name: Tests

on: [ push, pull_request ]

env:
  USE_PYTHON_VERSION: 3.10.9
  DJANGO_CONFIGURATION: Test

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: margin
          POSTGRES_PASSWORD: margin
          POSTGRES_USER: margin
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: run linters via pre-commit
        run: |
          pre-commit run --all --show-diff-on-failure --color=always
      - name: Run tests
        run: pytest
